---
title: Calculate Correlation
summary:  This notebook is to calculate and display statisitcal significance.
output: html_notebook
---


```{r}
library(tidyverse)
library(dplyr)
library(ggpubr)
```

Import data from CSV.  See /wrangle/survey_Wrangle.Rmd for code used to 
create the CSV.

```{r}
HAB_MRIP <- read.csv("../data_out/sarasota_clustered.csv")
```

```{r}
head(HAB_MRIP)

#http://www.sthda.com/english/wiki/wiki.php?id_contents=7312

# x and y are numeric vectors with the same length

cluster1 <- HAB_MRIP %>% filter(clust==1)
cluster2 <- HAB_MRIP %>% filter(clust==2)
cluster3 <- HAB_MRIP %>% filter(clust==3)
cluster4 <- HAB_MRIP %>% filter(clust==4)
cluster5 <- HAB_MRIP %>% filter(clust==5)
```


```{r}
cor.test(cluster1$mean_brevis_count, cluster1$catch_count, method=c("pearson", "kendall", "spearman")) 
cor.test(cluster2$mean_brevis_count, cluster2$catch_count, method=c("pearson", "kendall", "spearman")) 
cor.test(cluster3$mean_brevis_count, cluster3$catch_count, method=c("pearson", "kendall", "spearman"))
cor.test(cluster4$mean_brevis_count, cluster4$catch_count, method=c("pearson", "kendall", "spearman")) 
cor.test(cluster5$mean_brevis_count, cluster5$catch_count, method=c("pearson", "kendall", "spearman")) 




```


