---
title: Create FAMD Clusters
summary:  This notebook is used to create clusters of fish species and other vars
output: famd_cluster.csv
---


```{r}
library(readr)
library(dplyr)
library(Factoshiny)
```

```{r}

#input CSV which was created by survey_Wrangle.Rmd
HAB_MRIP <- read.csv("../data_out/sarasota.csv") %>% 
        mutate(year=as.character(year),month=as.character(month),MODE_FX = as.character(MODE_FX),AREA_X = as.character(AREA_X))

MRIP <- HAB_MRIP %>% select(c(common,catch_count,year,month,MODE_FX,AREA_X)) 

brevis <- HAB_MRIP %>% select(c(year,month,brevis_count,mean_brevis_count)) %>% distinct()

head(MRIP)
head(brevis)

```
```{r}
#https://www.youtube.com/watch?v=pmFCosCzRN8  
#Clustering with R (FactoMineR & Factoshiny)

result <- Factoshiny(MRIP)  #Wizard to create the code in the next chunk. 

#Code generated by Factoshiny
#res.PCA<-PCA(HAB_MRIP,ncp=Inf, scale.unit=FALSE,quali.sup=c(1),graph=FALSE)
#res.HCPC<-HCPC(res.PCA,nb.clust=5,kk=100,consol=FALSE,graph=FALSE)
#summary(res.HCPC)

```
```{r}
#view(res.HCPC$data.clust)
```

```{r}
head(MRIP)
#following code generated by FactoShiny
res.FAMD<-FAMD(MRIP,ncp=3,graph=FALSE)
plot.FAMD(res.FAMD,title="Graph of individuals and categories")
plot.FAMD(res.FAMD,axes=c(1,2),choix='var',title="Graph of the variables")
plot.FAMD(res.FAMD, choix='quanti',title="Correlation circle")
```


```{r}
#following code generated by FactoShiny
res.FAMD<-FAMD(MRIP,ncp=2,graph=FALSE)
res.HCPC<-HCPC(res.FAMD,nb.clust=5,kk=100,consol=FALSE,graph=FALSE)
plot.HCPC(res.HCPC,choice='tree',title='Hierarchical tree')
plot.HCPC(res.HCPC,choice='map',draw.tree=FALSE,title='Catch Survey Clusters')
plot.HCPC(res.HCPC,choice='3D.map',ind.names=FALSE,centers.plot=FALSE,angle=60,title='Hierarchical tree on the factor map')

#view(res.HCPC$data.clust)
```
```{r}

#Try zooming into the clusters by removing high catch counts. 
MRIP_tight <- MRIP %>% filter(catch_count<400)
head(MRIP_tight)

#following code generated by FactoShiny
#Try various numbers of dimensions and clusters.  
res.FAMD<-FAMD(MRIP_tight,ncp=5,graph=FALSE)
res.HCPC<-HCPC(res.FAMD,nb.clust=4,kk=100,consol=FALSE,graph=FALSE)
plot.HCPC(res.HCPC,choice='tree',title='Hierarchical tree')
plot.HCPC(res.HCPC,choice='map',draw.tree=FALSE,title='Catch Survey Clusters')
plot.HCPC(res.HCPC,choice='3D.map',ind.names=FALSE,centers.plot=FALSE,angle=60,title='Hierarchical tree on the factor map')

#view(res.HCPC$data.clust)
```


```{r}
clusters_out <- res.HCPC$data.clust %>% 
                inner_join(brevis,by = c("year","month")) 

head(clusters_out)
```


```{r}
write.csv(clusters_out,"../data_out/sarasota_clustered.csv", row.names = FALSE)


```

